version: "3"

services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile

    restart: always
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart : always
    ports:
      - "8081:8081"
    deploy:
      mode: replicas
      replicas: 1
    env_file:
      - .env
    environment:
      - DSN="host=postgres port=5432 user=${POSTGRES_USER} password=${POSTGRES_USER} dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  postgres:
    image: "postgres:14.0"
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgres/data
